config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :pets

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/pet.rb
class Pet < ApplicationRecord
  validates :name, presence: true

  def found_days_ago
    (Date.today - found_on).to_i
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pets_controller.rb
class PetsController < ApplicationController
  before_action :set_pet, only: [:show, :edit, :update, :destroy]
  def index
    @pets = Pet.all
  end

  def show
  end

  def new
    @pet = Pet.new
  end

  def create
    @pet = Pet.new(pet_params)
    @pet.save
    redirect_to pets_path
  end

  def edit
  end

  def update
    @pet.update(pet_params)
    redirect_to pet_path(@pet)
  end

  def destroy
    @pet.destroy
    redirect_to pets_path
  end

  private

  def pet_params
    params.require(:pet).permit(:name, :address, :species, :found_on)
  end

  def set_pet
    @pet = Pet.find(params[:id])
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pets_helper.rb
module PetsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>LostPets</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/pets/_form.html.erb
<div class="container">
  <%= simple_form_for @pet do |f| %>
  <%= f.input :name %>
  <%= f.input :address %>
  <%= f.input :species %>
  <%= f.input :found_on, as: :date %>
  <%= f.button :submit, class: 'btn btn-danger w-100' %>
  <% end %>
</div>

<%#= form_for @pet do |f| %>
<%#= f.label :name, "Enter a name" %>
<%#= f.text_field :name %>
<%#= f.label :address, "Enter a address" %>
<%#= f.text_field :address %>
<%#= f.label :species, "Enter a species" %>
<%#= f.text_field :species %>
<%#= f.label :found_on, "Enter a date" %>
<%#= f.date_field :found_on %>
<%#= f.submit %>
<%# end %>

app/views/pets/edit.html.erb
<h2>Edit your pet</h2>

<%= render 'form' %>

app/views/pets/index.html.erb
<div class="container">
  <h1>All my pets</h1>
  <ul>
    <% @pets.each do |pet| %>
    <li>
      <h2><%= link_to pet.name, pet_path(pet) %></h2>
      <p><%= pet.species %></p>
      <p>Found <%= pet.found_days_ago %> days ago</p>
    </li>
    <% end %>
  </ul>
  <%= link_to "Create new pet", new_pet_path, class: 'btn btn-primary' %>
</div>

app/views/pets/new.html.erb
<%= render 'form' %>

app/views/pets/show.html.erb
<h1><%= @pet.name %></h1>
<h2><%= @pet.address %></h2>
<h2><%= @pet.species %></h2>
<h2>Found <%= @pet.found_days_ago %> days ago</h2>

<%= link_to 'See all pets', pets_path %>
<%= link_to 'Edit', edit_pet_path(@pet) %>
<%= link_to 'Delete', pet_path(@pet), method: :delete %>